const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Whisk flour, sugar, baking powder, baking soda and kosher salt together in a bowl. `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `A popular sandwich made from ground meats that are formed into a patty, cooked, and placed between two halves of a bun`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `A thoroughly shaken or blended drink made of milk, a flavoring syrup, and often ice cream`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Complete meal with and and goto bread as sides toasted with butter `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: ` Like eggs? Just go for it. Protein packed eggs . Great for body building  `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Just swim in the oreo dream and dive to the deepest oreo dreams forever and ever.`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Crispy bacon with pan tossed butter.Like eggs? Just go for it. Protein packed for winter's`,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Burger ! Burger ! buerger on the way all the way from America the best and the classic favourite. `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Quaratine buddy stay safe ! stay well and dive in.`,
  },
];
export default menu;
